- name: Configuring Catalogue Server
  hosts: catalogue
  become: yes
  tasks:
  - name: Disable default NodeJS
    ansible.builtin.command: dnf module disable nodejs -y

  - name: Enable nodejs Version 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: Installing nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present 

  - name: creating roboshop user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app
  
  - name: crating app drectory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Downloading Application code
    ansible.builtin.get_url:
       url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
       dest: /tmp/catalogue.zip


  - name: Extract Catalogue code
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: Installing dependencies
    community.general.npm:
      path: /app

  - name: copying service file to system directory
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: Daemon-reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: Enable and start Catalogue service
    ansible.builtin.service:
      name: catalogue
      state: started
      enabled: yes
  
  - name: copy mongodb repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: Installing mongodb-host
    ansible.builtin.dnf:
      name: mongodb-mongosh
      state: present

  - name: check products loaded or not
    ansible.builtin.command: mongosh --host mongodb.daws84s.site --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output

  - name: print catalogue output
    ansible.builtin.debug:
      msg: "{{ catalogue_output }}"

  - name: load products
    ansible.builtin.shell: mongosh --host mongodb.daws84s.site < /app/db/master-data.js
    when: catalogue_output.stdout | int < 0